# Generated by Django 4.2.13 on 2024-07-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_age_alter_myuser_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='age',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
