version: "3"

services:
  front-end:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: frontend
    networks:
      - ft_trans
    restart: unless-stopped

  back-end:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    container_name: backend
    volumes:
      - ./back:/code
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ft_trans
    restart: unless-stopped
    env_file:
      - ./back/.env

  db:
    container_name: database
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./back/.env
    networks:
      - ft_trans
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - ft_trans
    restart: unless-stopped

networks:
  ft_trans:

volumes:
  data:
