# Generated by Django 4.2.14 on 2024-07-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='fname',
            field=models.CharField(default='abc', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='lname',
            field=models.CharField(default='abc', max_length=30),
            preserve_default=False,
        ),
    ]
