# Generated by Django 4.2.14 on 2024-07-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0002_appuser_fname_appuser_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='fname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='lname',
            new_name='lastName',
        ),
    ]
