# Generated by Django 4.2.14 on 2024-07-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0003_rename_fname_appuser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
