# Generated by Django 4.2.14 on 2024-07-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0004_appuser_country_appuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='location',
        ),
    ]
