# Generated by Django 4.2.14 on 2024-07-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0005_remove_appuser_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='genre',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='insta_username',
            new_name='instaUsername',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='kik_username',
            new_name='kikUsername',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='snap_username',
            new_name='snapUsername',
        ),
    ]
