# Generated by Django 4.2.14 on 2024-08-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0008_tag_tagsperuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagsperuser',
            old_name='item',
            new_name='tag',
        ),
    ]
