# Generated by Django 4.2.14 on 2024-08-05 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0011_appuser_groups_appuser_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
    ]
