# Generated by Django 4.2.14 on 2024-08-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0013_remove_appuser_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='kikUsername',
            new_name='tiktokUsername',
        ),
    ]
