# Generated by Django 4.2.14 on 2024-08-06 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0014_rename_kikusername_appuser_tiktokusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_user', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('viewer', 'viewed')},
            },
        ),
    ]
