# Generated by Django 4.2.14 on 2024-08-09 09:14

from django.db import migrations, models
import django.db.models.deletion
import usrinfo.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0017_appuser_aboutme_appuser_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image_background', models.ImageField(default='images/default.png', upload_to='images', validators=[usrinfo.validators.max_size_validator])),
            ],
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='instaUsername',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='snapUsername',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='tiktokUsername',
        ),
        migrations.AddField(
            model_name='appuser',
            name='instagram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_users', to='usrinfo.platform'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='snapchat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapchat_users', to='usrinfo.platform'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='tiktok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiktok_users', to='usrinfo.platform'),
        ),
    ]
