# Generated by Django 4.2.14 on 2024-08-09 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0019_platform_slug_alter_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='snapchat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_platforms', to='usrinfo.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_platforms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='platforms',
            field=models.ManyToManyField(related_name='users', through='usrinfo.UserPlatform', to='usrinfo.platform'),
        ),
    ]
