# Generated by Django 4.2.14 on 2024-08-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0020_alter_appuser_instagram_alter_appuser_snapchat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='snapchat',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='tiktok',
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=65, unique=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
