# Generated by Django 5.0.7 on 2024-07-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('snap_username', models.CharField(blank=True, max_length=255, null=True)),
                ('kik_username', models.CharField(blank=True, max_length=255, null=True)),
                ('insta_username', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], max_length=1)),
                ('interests', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
